name: dataViz

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter

  launcher_assist: ^1.1.3
  cupertino_icons: ^0.1.2
  permission_handler: '^3.0.0'
  sms: ^0.2.0
  location: ^2.3.5
  geolocator: '^4.0.0'

  call_log: ^2.0.0

  photo_manager: ^0.3.3

  device_calendar: ^0.0.2

  contacts_service: ^0.0.9

  dots_indicator: ^0.0.5

  speech_recognition: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:

  - assets/logo_dataviz_1.png
  - assets/dataViz_logo2.png
  - assets/mabu-lightbulb.png
  - assets/light.png
  - assets/Data-Science-vs.-Big-Data-vs.jpg
  - assets/blomma_test.jpg
  - assets/test1.jpg
  - assets/lamp1.png
  - assets/forgetmepic.jpg
  - assets/camera1.jpg
  - assets/camera2.jpeg
  - assets/camera3.jpg
  - assets/camera4.jpg
  - assets/activity1.jpeg
  - assets/activity2.jpeg
  - assets/activity3.jpeg
  - assets/calender1.jpg
  - assets/calender2.jpg
  - assets/calender3.jpeg
  - assets/calender4.jpg
  - assets/sensors1.jpg
  - assets/audiofile1.jpg
  - assets/audiofile2.jpg
  - assets/phone1.jpg
  - assets/phone2.jpg
  - assets/location_map.jpg
  - assets/location_code.jpg
  - assets/protest.jpg
  - assets/socialmedia.jpg
  - assets/cash.jpg

  fonts:
  - family: Modak-Regular
    fonts:
    - asset: assets/Modak-Regular.ttf

  - family: Roboto_Condensed
    fonts:
      - asset: assets/Roboto_Condensed/RobotoCondensed-Bold.ttf

  - family: Abel-Regular
    fonts:
    - asset: assets/Abel-Regular.ttf
      weight: 900


  uses-material-design: true

